# Generated by Django 4.2.6 on 2023-11-18 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='postContent',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
